# Generated by Django 5.2.3 on 2025-07-24 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_quiz_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='user_answers',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
