# Generated by Django 5.2.3 on 2025-07-24 01:28

from django.db import migrations
from django.contrib.auth.models import User

def fix_quiz_users(apps, schema_editor):
    Quiz = apps.get_model('pages', 'Quiz')
    default_user = User.objects.first()
    Quiz.objects.filter(user__isnull=True).update(user=default_user)

class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_quiz_user_answers'),
    ]

    operations = [
        migrations.RunPython(fix_quiz_users),
    ]
